// The ARCHIVED split-screen build: it loads, and one player shopping does not
// freeze the other one out.
//
// Reported as "if the shop opens on one side of the screen in the local version
// currently the other side is useless, but the other side should still be able
// to select characters and open the other person's shop like normal". The shop
// was one panel behind a full-screen opaque scrim: the other half of the screen
// was both invisible and unclickable.
//
// This also serves as the legacy build's load check. That build is GENERATED by
// art/port_to_legacy.py, and the failure mode of a porting script is a page
// that dies at load with a blank screen - which has happened, from a guard that
// matched an identifier inside a comment.
const H = require('./harness');

(async () => {
    const browser = await H.launch();
    await H.startServer();
    const { check, section, finish } = H.makeChecker();
    const page = await H.newPage(browser);
    await H.boot(page, { clearStorage: true, path: '/legacy/local-splitscreen.html' });

    section('The ported build loads at all:');
    const boot = await page.evaluate(() => ({
        hasDebug: !!window.ACDebug,
        coop: !!(window.ACDebug && window.ACDebug.COOP_RESPAWN_FRAMES),
        panels: ['shop-panel-p1', 'shop-panel-p2'].every(id => !!document.getElementById(id)),
    }));
    check('ACDebug is present, so no load-time exception', boot.hasDebug, JSON.stringify(boot));
    check('the co-op respawn rule came across', boot.coop === true, JSON.stringify(boot));
    check('and there are two shop panels', boot.panels === true, JSON.stringify(boot));
    check('no page errors', page.errors.length === 0, JSON.stringify(page.errors.slice(0, 3)));

    section("One player's shop leaves the other side alone:");
    const open = await page.evaluate(() => {
        const D = window.ACDebug;
        D.openShop('p1');
        const vis = id => {
            const el = document.getElementById(id);
            return !!el && el.getClientRects().length > 0;
        };
        // The point of the whole change: is the OTHER side reachable? Asked of
        // the browser's own hit-testing, not of the CSS - a scrim that covers
        // the screen is invisible to a computed-style check on the button.
        const hitTop = (sel) => {
            const el = document.querySelector(sel);
            if (!el) return 'missing';
            const r = el.getBoundingClientRect();
            const top = document.elementFromPoint(r.left + r.width / 2, r.top + r.height / 2);
            return el === top || el.contains(top) ? 'reachable' : 'blocked by ' + (top && top.id
                ? '#' + top.id : (top && top.className) || 'something');
        };
        return {
            p1Panel: vis('shop-panel-p1'), p2Panel: vis('shop-panel-p2'),
            p2Card: hitTop('#p2-grid .fighter-btn'),
            p2Shop: hitTop('[data-shop-side="p2"]'),
            p1Card: hitTop('#p1-grid .fighter-btn'),
        };
    });
    check("P1's store is open", open.p1Panel === true, JSON.stringify(open));
    check("P2's store is not, since P2 did not open it", open.p2Panel === false, JSON.stringify(open));
    check('P2 can still click their roster', open.p2Card === 'reachable', JSON.stringify(open));
    check('P2 can still open their own store', open.p2Shop === 'reachable', JSON.stringify(open));

    section('Both stores can be open at once, and close independently:');
    const both = await page.evaluate(() => {
        const D = window.ACDebug;
        D.openShop('p2');
        const vis = id => document.getElementById(id).getClientRects().length > 0;
        const bothOpen = { p1: vis('shop-panel-p1'), p2: vis('shop-panel-p2') };
        document.querySelector('[data-shop-close="p1"]').click();
        const afterP1 = { p1: vis('shop-panel-p1'), p2: vis('shop-panel-p2'),
                          overlay: document.getElementById('shop-screen').style.display };
        document.querySelector('[data-shop-close="p2"]').click();
        const afterP2 = { p1: vis('shop-panel-p1'), p2: vis('shop-panel-p2'),
                          overlay: document.getElementById('shop-screen').style.display };
        return { bothOpen, afterP1, afterP2 };
    });
    check('opening P2 does not close P1',
        both.bothOpen.p1 === true && both.bothOpen.p2 === true, JSON.stringify(both.bothOpen));
    check('closing P1 leaves P2 open',
        both.afterP1.p1 === false && both.afterP1.p2 === true, JSON.stringify(both.afterP1));
    check('and the overlay only goes away once both are closed',
        both.afterP1.overlay !== 'none' && both.afterP2.overlay === 'none',
        JSON.stringify({ afterP1: both.afterP1, afterP2: both.afterP2 }));

    section('Each store shows its own side, not a shared one:');
    const sides = await page.evaluate(() => {
        const D = window.ACDebug;
        D.openShop('p1');
        D.openShop('p2');
        const text = id => (document.getElementById(id) || {}).textContent || '';
        return {
            t1: text('shop-title-p1'), t2: text('shop-title-p2'),
            cards1: document.querySelectorAll('#shop-list-p1 .shop-card').length,
            cards2: document.querySelectorAll('#shop-list-p2 .shop-card').length,
        };
    });
    check('P1 panel is titled for P1', /Player 1/.test(sides.t1), JSON.stringify(sides));
    check('P2 panel is titled for P2', /Player 2/.test(sides.t2), JSON.stringify(sides));
    check('both panels rendered their cards',
        sides.cards1 > 1 && sides.cards2 > 1, JSON.stringify(sides));

    section('The canonical-URL redirect does not fire on a local host:');
    const url = page.url();
    check('still on the legacy path, not sent to a /local that is not served here',
        /local-splitscreen/.test(url), url);

    await finish(browser, page);
})();
