# -*- coding: utf-8 -*-
"""Where everything lives, generated from the code rather than written down.

    python art/outline.py            print the outline
    python art/outline.py --write    write docs/MAP.md

WHY NOT JUST SPLIT THE FILE. Because the decision was to keep it, and keeping it
is defensible: the sync machinery in art/sync_local.py - the definition scanner,
the CSS parser, the markup differ, the nine interface lists - all assume each
build is ONE file it can read end to end. Splitting would retire the only thing
keeping the two builds honest, on the same day, to fix a problem that is really
"I cannot find anything".

So fix that problem instead. This is a map.

WHY IT IS GENERATED. A hand-written index of an 11,000-line file is wrong within
a week, and worse than nothing once it is - you trust it, it sends you to the
wrong place, you stop trusting any of it. Regenerating it from the source means
it is either right or obviously missing.

ANCHORS ARE TEXT, NOT LINE NUMBERS, for the same reason. A line number is stale
after the next edit; `function netApplyRemote` is findable forever.
"""
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

FILES = [
    ('index.html', 'The online build. Everything inside bootGame() can see the '
                   'DOM and the scene; shared/ modules cannot see in here.'),
    ('shared/common.js', 'The game. Both builds load this, so nothing in it may '
                         'reach into bootGame().'),
    ('shared/roster.js', 'Fighters, costs and upgrade rules. Pure data.'),
    ('shared/animation.js', 'Rig timing. Pure data.'),
    ('shared/props.js', 'Arena scenery, built from THREE at load.'),
    ('shared/characters.js', 'Character meshes and materials.'),
    ('shared/i18n.js', 'English, Spanish, French.'),
    ('shared/touch.js', 'The mobile control scheme. Online only.'),
    ('shared/challenges.js', 'The three daily challenges.'),
    ('shared/account.js', 'Sign-in and the cloud save.'),
    ('shared/telemetry.js', 'Balance counts and error reports, aggregate-only.'),
]

# A banner: a comment line of ==== or ---- with a title on the line after it.
BANNER = re.compile(r'^//\s*[=-]{10,}\s*$')
# Top-level definitions, at column zero so nested helpers stay out of the map.
DEF = re.compile(
    r'^(?:async\s+)?function\s+([A-Za-z_$][\w$]*)'
    r'|^class\s+([A-Za-z_$][\w$]*)'
    r'|^const\s+([A-Z][A-Z0-9_]{2,})\s*='        # SHOUTING constants only
)


def summarise(lines, i):
    """The first sentence of the comment above a definition, if there is one."""
    out = []
    j = i - 1
    while j >= 0 and lines[j].startswith('//'):
        out.append(lines[j][2:].strip())
        j -= 1
        if len(out) > 6:
            break
    if not out:
        return ''
    text = ' '.join(reversed(out))
    text = re.sub(r'\s+', ' ', text).strip()
    m = re.match(r'(.{10,110}?[.!?])(\s|$)', text)
    return (m.group(1) if m else text[:110]).strip()


def outline(rel):
    p = os.path.join(ROOT, rel.replace('/', os.sep))
    if not os.path.exists(p):
        return []
    text = io.open(p, encoding='utf-8').read()
    # In the HTML build, only the script body has definitions worth mapping.
    if rel.endswith('.html'):
        i = text.find('function bootGame()')
        if i > 0:
            text = text[i:]
    lines = text.split(chr(10))
    rows = []
    for i, l in enumerate(lines):
        if BANNER.match(l) and i + 1 < len(lines) and lines[i + 1].startswith('//'):
            title = lines[i + 1][2:].strip()
            if title and not BANNER.match(lines[i + 1]):
                rows.append(('section', title, ''))
            continue
        m = DEF.match(l)
        if m:
            name = m.group(1) or m.group(2) or m.group(3)
            rows.append(('def', name, summarise(lines, i)))
    return rows


def main():
    out = []
    out.append('# Where everything lives')
    out.append('')
    out.append('Generated by `python art/outline.py --write`. **Do not edit by hand** -')
    out.append('regenerate it. A hand-maintained index of an 11,000-line file is wrong')
    out.append('within a week and worse than nothing once it is.')
    out.append('')
    out.append('Anchors are TEXT, not line numbers: search for `function netApplyRemote`,')
    out.append('not for a line that moved three edits ago.')
    out.append('')
    out.append('The file is deliberately not split. `art/sync_local.py` keeps the two')
    out.append('builds in step by reading each one end to end, and splitting would retire')
    out.append('that machinery to solve a problem this file solves instead.')
    out.append('')

    total = 0
    for rel, blurb in FILES:
        rows = outline(rel)
        if not rows:
            continue
        defs = [r for r in rows if r[0] == 'def']
        total += len(defs)
        out.append('## `%s`' % rel)
        out.append('')
        out.append(blurb)
        out.append('')
        out.append('%d top-level definitions.' % len(defs))
        out.append('')
        for kind, name, note in rows:
            if kind == 'section':
                out.append('')
                out.append('**%s**' % name)
                out.append('')
            else:
                out.append('- `%s`%s' % (name, ' — ' + note if note else ''))
        out.append('')

    text = chr(10).join(out) + chr(10)
    if '--write' in sys.argv:
        d = os.path.join(ROOT, 'docs')
        if not os.path.isdir(d):
            os.makedirs(d)
        io.open(os.path.join(d, 'MAP.md'), 'w', encoding='utf-8', newline=chr(10)).write(text)
        print('docs/MAP.md: %d definitions across %d files' % (total, len(FILES)))
    else:
        print(text)
    return 0


if __name__ == '__main__':
    sys.exit(main())
